db:
  connection: "postgres://pvz:pvzpassword@db-pvz:5432/pvz?sslmode=disable"

http_server:
  http_port: "8080"
  timeout_ms: 1000

grps:
  grps_port: "3000"

prometheus:
  prometheus_port: "9000"

auth:
  dummy_token_prefix: "dummy-token-for-"
  jwt_secret: "super-secret-key"
  jwt_expiration_minutes: 60

limits:
  pagination_limit: 10