services:
  db-pvz:
    image: postgres:12
    environment:
      POSTGRES_DB: pvz
      POSTGRES_USER: pvz
      POSTGRES_PASSWORD: pvzpassword
    ports:
      - "5445:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pvz"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD:-3s}"
