global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'pvz-project'

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
         - targets: ['localhost:9000']